version: '3'

services:
  application:
    build: sample_app/
    ports:
     - 80:80
  abc_proxy:
    build: proxy/
    env_file:
      - proxy/.env 
    ports:
     - 5000:5000
    environment:
     - ABC_REDIRECT_HOST=https://localhost
  nginx:
    build: nginx/ 
    ports:
     - 443:443
     - 8080:80
    depends_on:
     - application
     - abc_proxy 
    environment:
     - APP_PROXY_TARGET=application
     - APP_PROXY_PORT=80
     - ABC_PROXY_TARGET=abc_proxy
     - ABC_PROXY_PORT=5000
     - APP_PROXY_PROTOCOL=http
     - DNS_RESOLVER=127.0.0.11
